"""
vision_utils.py — Helper functions for Multimodal RAG
Passes images to Ollama's Vision model (llava:7b) to generate text summaries
that can be appended to the document's text context.
"""

import ollama
import io
import base64
from PIL import Image

def summarize_image(image_bytes: bytes) -> str:
    """
    Send an image to the local llava:7b model and return a description.
    
    Args:
        image_bytes: The raw bytes of the image file (e.g., extracted from PDF or PPTX)
        
    Returns:
        A text description of the image content generated by the vision model.
    """
    # Verify it's actually an image we can process
    try:
        # We can just open it to verify it's a valid image blob before sending it
        img = Image.open(io.BytesIO(image_bytes))
        img.verify()
    except Exception as e:
        print(f"Skipping invalid image blob: {e}")
        return ""
        
    try:
        # Ollama expects base64 encoded strings
        b64_image = base64.b64encode(image_bytes).decode('utf-8')
        
        # Call the local vision model
        response = ollama.chat(
            model='llava:7b',
            messages=[{
                'role': 'user',
                'content': (
                    "Please describe this image, chart, or diagram in detail. "
                    "What are the main titles, labels, trends, or key takeaways?"
                ),
                'images': [b64_image]
            }]
        )
        description = response.get('message', {}).get('content', '').strip()
        
        if description:
            return f"\n\n[Image/Diagram Description: {description}]\n"
            
    except Exception as e:
        print(f"Ollama Vision API error (llava:7b): {e}")
        
    return ""
